Remove optional mfhd
pulibrary/requests pull request #898
Opened 2021-02-22 20:38 UTC by carolyncole

Since the catalog is always passing a MFHD, and we no longer show the other options url, we can stop supporting multiple mfhds in one request.

Most of the changes were to add the mfhd to all the test, most of which did not already have it.

2021-02-23 13:33 UTC, kevinreiss requested changes
This looks great (and much simplified), let's do a bit more testing on this for.

1. Charged/missing materials.
2. ReCAP materials Princeton Owns
3. Aeon Multi-volume requests.

2021-02-23 13:41 UTC, carolyncole commented
Special Collections Multi item:
https://catalog-staging.princeton.edu/requests/9703142?mfhd=9526320&source=pulsearch
https://catalog.princeton.edu/requests/9703142?mfhd=9526320&source=pulsearch

Charged: 
https://catalog-staging.princeton.edu/requests/496904?mfhd=540374&source=pulsearch
https://catalog.princeton.edu/requests/496904?mfhd=540374&source=pulsearch

Recap:
https://catalog-staging.princeton.edu/requests/11053566?mfhd=10760495&source=pulsearch
https://catalog.princeton.edu/requests/11053566?mfhd=10760495&source=pulsearch

2021-02-25 03:37 UTC, kevinreiss approved these changes

2021-02-25 03:41 UTC, kevinreiss approved these changes

2021-02-25 03:41 UTC, merged