Extending the Requests::Patron#current_patron method to handle 429 HTTP responses from the BibData endpoint
pulibrary/requests pull request #993
Opened 2021-06-16 14:28 UTC by jrgriffiniii

Resolve #916

2021-06-16 17:13 UTC, carolyncole requested changes
Overall I like the refactor into smaller methods.  I would like to simplify the logic in api_request_patron so that folks do not need to understand exception flow.

2021-06-16 17:13 UTC, carolyncole commented on app/models/requests/patron.rb
> +        case response.status
@jrgriffiniii I find this odd that you are utilizing exceptions as part of the code logic within a single routine.  I could see if this routine did not handle the error, but as part of the same method it seems overly complex.  I like your use of a case statement over the elseif.  Maybe just move the actual code into the case?

2021-06-23 21:34 UTC, kevinreiss commented on app/models/requests/patron.rb
> +    class ServerError < StandardError; end
@jrgriffiniii Since we no longer reference these errors in the code can these error class declarations be removed?

2021-06-25 19:00 UTC, kevinreiss approved these changes

2021-06-25 19:01 UTC, merged